# Generated by Django 5.2.12 on 2026-08-11 19:46

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('color', models.CharField(default='#4F46E5', max_length=7, validators=[django.core.validators.RegexValidator(message='Informe uma cor hexadecimal válida (ex.: #4F46E5).', regex='^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')], verbose_name='cor')),
                ('icon', models.CharField(blank=True, max_length=64, validators=[django.core.validators.RegexValidator(message="Ícone deve ser um identificador kebab-case (ex.: 'book-open').", regex='^[a-z0-9-]{1,64}$')], verbose_name='ícone')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='fixada')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='posição')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ('-is_pinned', 'position', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=180, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('color', models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator(message='Informe uma cor hexadecimal válida (ex.: #4F46E5).', regex='^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')], verbose_name='cor')),
                ('icon', models.CharField(blank=True, max_length=64, validators=[django.core.validators.RegexValidator(message="Ícone deve ser um identificador kebab-case (ex.: 'book-open').", regex='^[a-z0-9-]{1,64}$')], verbose_name='ícone')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='favorita')),
                ('is_archived', models.BooleanField(default=False, verbose_name='arquivada')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='posição')),
                ('path', models.CharField(db_index=True, editable=False, max_length=444)),
                ('depth', models.PositiveSmallIntegerField(default=0, editable=False)),
            ],
            options={
                'verbose_name': 'pasta',
                'verbose_name_plural': 'pastas',
                'ordering': ('position', 'name'),
            },
        ),
    ]
