# Generated by Django 5.2.12 on 2026-08-11 19:46

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='dono'),
        ),
        migrations.AddField(
            model_name='folder',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='organization.category', verbose_name='categoria'),
        ),
        migrations.AddField(
            model_name='folder',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='dono'),
        ),
        migrations.AddField(
            model_name='folder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='organization.folder', verbose_name='pasta pai'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['owner', 'position'], name='organizatio_owner_i_0d6ef7_idx'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(models.F('owner'), django.db.models.functions.text.Lower('name'), name='unique_category_name_per_owner'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['owner', 'parent'], name='organizatio_owner_i_7d7fe1_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['owner', 'is_archived'], name='organizatio_owner_i_f6c8cb_idx'),
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(models.F('owner'), models.F('parent'), django.db.models.functions.text.Lower('name'), condition=models.Q(('parent__isnull', False)), name='unique_folder_name_per_parent'),
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(models.F('owner'), models.F('category'), django.db.models.functions.text.Lower('name'), condition=models.Q(('parent__isnull', True)), name='unique_root_folder_name_per_category'),
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.CheckConstraint(condition=models.Q(('parent', models.F('id')), _negated=True), name='folder_cannot_be_its_own_parent'),
        ),
    ]
