# Generated by Django 5.2.12 on 2026-08-13 15:37

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_category_deleted_at_folder_deleted_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='unique_category_name_per_owner',
        ),
        migrations.RemoveConstraint(
            model_name='folder',
            name='unique_folder_name_per_parent',
        ),
        migrations.RemoveConstraint(
            model_name='folder',
            name='unique_root_folder_name_per_category',
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(models.F('owner'), django.db.models.functions.text.Lower('name'), condition=models.Q(('deleted_at__isnull', True)), name='unique_category_name_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(models.F('owner'), models.F('parent'), django.db.models.functions.text.Lower('name'), condition=models.Q(('deleted_at__isnull', True), ('parent__isnull', False)), name='unique_folder_name_per_parent'),
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(models.F('owner'), models.F('category'), django.db.models.functions.text.Lower('name'), condition=models.Q(('deleted_at__isnull', True), ('parent__isnull', True)), name='unique_root_folder_name_per_category'),
        ),
    ]
