# Generated by Django 5.2.12 on 2026-08-11 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_folder_requires_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='organization.category', verbose_name='categoria'),
        ),
    ]
