# Generated by Django 5.2.12 on 2026-08-11 19:46

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0002_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=250, verbose_name='texto')),
                ('is_done', models.BooleanField(default=False, verbose_name='concluído')),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'item de checklist',
                'verbose_name_plural': 'itens de checklist',
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('title', models.CharField(max_length=250, verbose_name='título')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('status', models.CharField(choices=[('todo', 'A fazer'), ('in_progress', 'Em progresso'), ('done', 'Concluída')], db_index=True, default='todo', max_length=16, verbose_name='status')),
                ('priority', models.IntegerField(choices=[(0, 'Baixa'), (1, 'Média'), (2, 'Alta'), (3, 'Urgente')], db_index=True, default=1, verbose_name='prioridade')),
                ('starts_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='início')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='fim')),
                ('all_day', models.BooleanField(default=False, verbose_name='dia inteiro')),
                ('reminder_at', models.DateTimeField(blank=True, null=True, verbose_name='lembrete')),
                ('completed_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='concluída em')),
                ('recurrence_rule', models.CharField(blank=True, max_length=250, verbose_name='recorrência')),
                ('color', models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator(message='Informe uma cor hexadecimal válida (ex.: #4F46E5).', regex='^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')], verbose_name='cor')),
                ('position', models.FloatField(default=0, verbose_name='posição no quadro')),
                ('categories', models.ManyToManyField(blank=True, related_name='tasks', to='organization.category')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='content.document', verbose_name='documento vinculado')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='organization.folder', verbose_name='pasta')),
            ],
            options={
                'verbose_name': 'tarefa',
                'verbose_name_plural': 'tarefas',
                'ordering': ('position', '-priority', 'starts_at'),
            },
        ),
    ]
