# Generated by Django 5.2.12 on 2026-08-13 15:37

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_board_deleted_at_task_deleted_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='board',
            name='unique_board_name_per_owner',
        ),
        migrations.RemoveConstraint(
            model_name='board',
            name='unique_default_board_per_owner',
        ),
        migrations.AddConstraint(
            model_name='board',
            constraint=models.UniqueConstraint(models.F('owner'), django.db.models.functions.text.Lower('name'), condition=models.Q(('deleted_at__isnull', True)), name='unique_board_name_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='board',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_default', True)), fields=('owner',), name='unique_default_board_per_owner'),
        ),
    ]
