# Generated by Django 5.2.12 on 2026-08-10 23:06

import content.models
import django.contrib.postgres.search
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('file', models.FileField(max_length=400, upload_to=content.models.attachment_upload_path, verbose_name='arquivo')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='nome original')),
                ('title', models.CharField(blank=True, max_length=250, verbose_name='título')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('kind', models.CharField(choices=[('image', 'Imagem'), ('audio', 'Áudio'), ('video', 'Vídeo'), ('pdf', 'PDF'), ('document', 'Documento'), ('archive', 'Compactado'), ('other', 'Outro')], db_index=True, default='other', max_length=16, verbose_name='tipo')),
                ('mime_type', models.CharField(blank=True, max_length=150)),
                ('size', models.PositiveBigIntegerField(default=0, verbose_name='tamanho em bytes')),
                ('checksum', models.CharField(blank=True, db_index=True, max_length=64)),
            ],
            options={
                'verbose_name': 'anexo',
                'verbose_name_plural': 'anexos',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('title', models.CharField(max_length=250, verbose_name='título')),
                ('content', models.TextField(blank=True, verbose_name='conteúdo')),
                ('content_format', models.CharField(choices=[('markdown', 'Markdown'), ('html', 'HTML'), ('plain', 'Texto puro')], default='markdown', max_length=10, verbose_name='formato')),
                ('excerpt', models.CharField(blank=True, editable=False, max_length=320, verbose_name='resumo')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('in_progress', 'Em progresso'), ('done', 'Finalizado')], db_index=True, default='draft', max_length=16, verbose_name='status')),
                ('color', models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator(message='Informe uma cor hexadecimal válida (ex.: #4F46E5).', regex='^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')], verbose_name='cor')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='favorita')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='fixada')),
                ('is_archived', models.BooleanField(default=False, verbose_name='arquivada')),
                ('word_count', models.PositiveIntegerField(default=0, editable=False)),
                ('last_viewed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
            ],
            options={
                'verbose_name': 'nota',
                'verbose_name_plural': 'notas',
                'ordering': ('-is_pinned', '-updated_at'),
            },
        ),
    ]
