# Generated by Django 5.2.12 on 2026-08-11 19:46

import content.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('kind', models.CharField(choices=[('note', 'Nota'), ('file', 'Arquivo'), ('spreadsheet', 'Planilha'), ('diagram', 'Diagrama'), ('canvas', 'Canvas')], db_index=True, default='note', max_length=16, verbose_name='tipo')),
                ('title', models.CharField(max_length=250, verbose_name='título')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('in_progress', 'Em progresso'), ('done', 'Finalizado')], db_index=True, default='draft', max_length=16, verbose_name='status')),
                ('color', models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator(message='Informe uma cor hexadecimal válida (ex.: #4F46E5).', regex='^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')], verbose_name='cor')),
                ('icon', models.CharField(blank=True, max_length=64, validators=[django.core.validators.RegexValidator(message="Ícone deve ser um identificador kebab-case (ex.: 'book-open').", regex='^[a-z0-9-]{1,64}$')], verbose_name='ícone')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='favorito')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='fixado')),
                ('is_archived', models.BooleanField(default=False, verbose_name='arquivado')),
                ('position', models.FloatField(default=0, verbose_name='posição')),
                ('content', models.TextField(blank=True, verbose_name='conteúdo')),
                ('content_format', models.CharField(choices=[('html', 'Texto rico'), ('markdown', 'Markdown'), ('plain', 'Texto puro')], default='html', max_length=10, verbose_name='formato')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='dados')),
                ('file', models.FileField(blank=True, max_length=400, null=True, upload_to=content.models.document_upload_path, verbose_name='arquivo')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='nome original')),
                ('mime_type', models.CharField(blank=True, max_length=150)),
                ('size', models.PositiveBigIntegerField(default=0, verbose_name='tamanho em bytes')),
                ('checksum', models.CharField(blank=True, db_index=True, max_length=64)),
                ('file_kind', models.CharField(blank=True, choices=[('image', 'Imagem'), ('audio', 'Áudio'), ('video', 'Vídeo'), ('pdf', 'PDF'), ('document', 'Documento'), ('archive', 'Compactado'), ('other', 'Outro')], db_index=True, max_length=16, verbose_name='categoria do arquivo')),
                ('excerpt', models.CharField(blank=True, editable=False, max_length=320, verbose_name='resumo')),
                ('word_count', models.PositiveIntegerField(default=0, editable=False)),
                ('search_text', models.TextField(blank=True, editable=False)),
                ('last_viewed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('attached_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='content.document', verbose_name='anexado a')),
            ],
            options={
                'verbose_name': 'documento',
                'verbose_name_plural': 'documentos',
                'ordering': ('-is_pinned', '-updated_at'),
            },
        ),
    ]
