# Generated by Django 5.2.12 on 2026-08-10 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='attachments', to='organization.category'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='organization.folder'),
        ),
    ]
