# Generated by Django 5.2.12 on 2026-08-10 23:06

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0002_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='dono'),
        ),
        migrations.AddField(
            model_name='note',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='notes', to='organization.category', verbose_name='categorias'),
        ),
        migrations.AddField(
            model_name='note',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='organization.folder', verbose_name='pasta'),
        ),
        migrations.AddField(
            model_name='note',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='dono'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='content.note'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='note_search_vector_gin'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['owner', 'status'], name='content_not_owner_i_2a63c4_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['owner', 'folder'], name='content_not_owner_i_e2b36d_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['owner', '-updated_at'], name='content_not_owner_i_c7ae45_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['owner', 'kind'], name='content_att_owner_i_25a45c_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['owner', '-created_at'], name='content_att_owner_i_e0ffd6_idx'),
        ),
    ]
