# Generated by Django 5.2.12 on 2026-08-11 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='dono'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['owner', 'kind'], name='content_doc_owner_i_2f2c58_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['owner', 'folder'], name='content_doc_owner_i_59a58d_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['owner', 'status'], name='content_doc_owner_i_272538_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['owner', '-updated_at'], name='content_doc_owner_i_da71a7_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['folder', '-updated_at'], name='content_doc_folder__cb1b96_idx'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('attached_to', models.F('id')), _negated=True), name='document_cannot_attach_to_itself'),
        ),
    ]
