# Generated by Django 5.2.12 on 2026-08-17 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_document_unique_document_title_per_kind_and_folder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ('-is_favorite', '-updated_at'), 'verbose_name': 'documento', 'verbose_name_plural': 'documentos'},
        ),
        migrations.RemoveField(
            model_name='document',
            name='is_pinned',
        ),
    ]
