# Generated by Django 5.2.12 on 2026-08-11 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_document_folder_not_null'),
        ('organization', '0004_cascade_in_db_guard_in_api'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='organization.folder', verbose_name='pasta'),
        ),
    ]
