# Generated by Django 5.2.12 on 2026-09-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_document_fts'),
        ('organization', '0004_remove_category_unique_category_name_per_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='documents', to='organization.category'),
        ),
    ]
