# Generated by Django 5.2.12 on 2026-09-25 03:42

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_document_categories'),
        ('organization', '0004_remove_category_unique_category_name_per_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='document',
            name='unique_document_title_per_kind_and_folder',
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(models.F('owner'), models.F('folder'), models.F('kind'), django.db.models.functions.text.Lower('title'), condition=models.Q(('attached_to__isnull', True), ('deleted_at__isnull', True)), name='unique_document_title_per_kind_and_folder'),
        ),
    ]
