# Generated by Django 5.2.12 on 2026-10-04 06:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_anexo_fora_do_nome_unico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('description', models.CharField(blank=True, default='', max_length=300, verbose_name='descrição')),
                ('kind', models.CharField(choices=[('note', 'Nota'), ('file', 'Arquivo'), ('spreadsheet', 'Planilha'), ('diagram', 'Diagrama'), ('canvas', 'Canvas')], max_length=16, verbose_name='tipo')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='dados')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='dono')),
            ],
            options={
                'verbose_name': 'modelo',
                'verbose_name_plural': 'modelos',
                'ordering': ('-updated_at',),
            },
        ),
    ]
