# Generated by Django 5.2.12 on 2026-10-05 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_resumo_sem_url_de_midia'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_read_only',
            field=models.BooleanField(default=False, verbose_name='somente leitura'),
        ),
    ]
