# Generated by Django 5.2.12 on 2026-10-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0013_somente_leitura"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="kind",
            field=models.CharField(
                choices=[
                    ("note", "Nota"),
                    ("file", "Arquivo"),
                    ("spreadsheet", "Planilha"),
                    ("diagram", "Diagrama"),
                    ("canvas", "Canvas"),
                    ("design", "Design"),
                ],
                db_index=True,
                default="note",
                max_length=16,
                verbose_name="tipo",
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="kind",
            field=models.CharField(
                choices=[
                    ("note", "Nota"),
                    ("file", "Arquivo"),
                    ("spreadsheet", "Planilha"),
                    ("diagram", "Diagrama"),
                    ("canvas", "Canvas"),
                    ("design", "Design"),
                ],
                max_length=16,
                verbose_name="tipo",
            ),
        ),
    ]
