# Generated by Django 5.2.12 on 2026-08-10 23:06

import django.db.models.deletion
import django.utils.timezone
import users.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='e-mail')),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name='nome completo')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=users.models.avatar_upload_path, verbose_name='avatar')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='equipe')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='entrou em')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='visto por último')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuário',
                'verbose_name_plural': 'usuários',
                'ordering': ('email',),
            },
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='preferences', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('theme', models.CharField(choices=[('light', 'Claro'), ('dark', 'Escuro'), ('system', 'Sistema')], default='system', max_length=10)),
                ('default_view', models.CharField(choices=[('dashboard', 'Dashboard'), ('calendar', 'Calendário'), ('board', 'Kanban')], default='dashboard', max_length=16)),
                ('sidebar_collapsed', models.BooleanField(default=False)),
                ('accent_color', models.CharField(default='#4F46E5', max_length=7)),
                ('editor_font_size', models.PositiveSmallIntegerField(default=16)),
                ('week_starts_on_monday', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'preferências',
                'verbose_name_plural': 'preferências',
            },
        ),
    ]
