# Generated by Django 5.2.12 on 2026-08-17 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_username_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='canvas_eraser_radius',
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='canvas_highlighter_opacity',
            field=models.PositiveSmallIntegerField(default=35),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='canvas_pen_size',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
