# Generated by Django 5.2.12 on 2026-08-20 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userpreferences_canvas_eraser_radius_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='ai_key',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='chave de IA'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='ai_model',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='modelo de IA'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='ai_provider',
            field=models.CharField(blank=True, choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('ollama', 'Ollama (local)')], default='', max_length=16, verbose_name='provedor de IA'),
        ),
    ]
