# Generated by Django 5.2.12 on 2026-08-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userpreferences_ai_key_userpreferences_ai_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='ai_base_url',
            field=models.URLField(blank=True, default='', max_length=300, verbose_name='URL base da IA'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='ai_provider',
            field=models.CharField(blank=True, choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('ollama', 'Ollama (local)'), ('custom', 'Personalizado (compatível com OpenAI)')], default='', max_length=16, verbose_name='provedor de IA'),
        ),
    ]
