# Generated by Django 5.2.12 on 2026-10-04 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_userpreferences_ai_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='home_layout',
            field=models.JSONField(blank=True, default=dict, verbose_name='layout do início'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='scratch_pad',
            field=models.TextField(blank=True, default='', verbose_name='rascunho do início'),
        ),
    ]
