# Generated by Django 5.2.12 on 2026-10-04 14:16

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_inicio_personalizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='home_cover',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.capa_upload_path, verbose_name='capa do início'),
        ),
    ]
