# Generated by Django 5.2.12 on 2026-10-10 10:44

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_capa_do_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='home_background',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.capa_upload_path, verbose_name='fundo do início'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='home_photo',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.capa_upload_path, verbose_name='foto do relógio'),
        ),
    ]
